os: osx
language: c
compiler: clang
osx_image: xcode10.1
cache:
  directories:
    - /usr/local/Homebrew/Library/Homebrew/vendor/bundle

before_install:
  - softwareupdate --install -a

script:
  - brew test-bot
  - brew cask audit ./Casks/*.rb
  - brew cask install -v ./Casks/*.rb
