os: osx
compiler: clang
osx_image: xcode10.1
cache:
  directories:
    - /usr/local/Homebrew/Library/Homebrew/vendor/bundle

before_install:
  - sudo chown -R "$USER" "$(brew --repo)"
  - travis_retry brew update
  - HOMEBREW_TAP_DIR="$(brew --repo "$TRAVIS_REPO_SLUG")"
  - mkdir -p "$HOMEBREW_TAP_DIR"
  - rm -rf "$HOMEBREW_TAP_DIR"
  - ln -s "$PWD" "$HOMEBREW_TAP_DIR"
  - brew install libyaml

jobs:
  include:
    - stage: test-bot
      script: brew test-bot
    - stage: formula
      script: brew audit --strict ./Formula/*.rb
    - script: brew install -v ./Formula/*.rb
    - script: brew test ./Formula/*.rb
    - stage: casks
      script: brew cask audit ./Casks/*.rb
    - script: brew cask install -v ./Casks/*.rb
