os: osx
compiler: clang
osx_image: xcode10
cache:
  directories:
    - /usr/local/Homebrew/Library/Homebrew/vendor/bundle

before_install:
  - rvm pkg install libyaml
  - sudo chown -R "$USER" "$(brew --repo)"
  - travis_retry brew update
  - HOMEBREW_TAP_DIR="$(brew --repo "$TRAVIS_REPO_SLUG")"
  - mkdir -p "$HOMEBREW_TAP_DIR"
  - rm -rf "$HOMEBREW_TAP_DIR"
  - ln -s "$PWD" "$HOMEBREW_TAP_DIR"

script:
  - brew test-bot
  - brew audit --strict ./Formula/*.rb
  - brew install -v ./Formula/*.rb
  - brew test ./Formula/*.rb
  - brew cask audit ./Casks/*.rb
  - brew cask install -v ./Casks/*.rb
