jobs:
- job: macOS
  pool:
    vmImage: macOS-10.13
  steps:
    - bash: |
        set -e
        sudo xcode-select --switch /Applications/Xcode_10.1.app/Contents/Developer
        brew update
        brew test-bot
        brew cask audit ./Casks/*.rb
        brew cask install -v ./Casks/*.rb
        brew cask style ./Casks/*.rb
